---
- hosts: rmhost
  tasks:
    - name: install vlc in remote machine
      apt: name=vlc update_cache=yes state=present  
    - name: install nginx
      apt: name=nginx update_cache=yes state=present
